version: '3.9'

services:
  server :
    container_name: server
    build: ./server/
    volumes :
      - ./server/server:/server
      - ./scripts/server.sh:/init.sh
    ports:
      - 6667:6667
    restart: on-failure
    entrypoint : ["./init.sh"]

  bot :
    container_name: bot
    depends_on:
      - server
    build: ./bot2.0/
    volumes :
      - ./bot2.0/bot:/bot
      - ./server/server:/server
      - ./scripts/bot.sh:/init.sh
    network_mode: "host"
    restart: on-failure
    entrypoint : ["./init.sh"]
