Bot must be invite to irc channel.
For commands type 'bot' followed by the command

The following are supported commands:    
[ ADD ] <login> //! Adds a new student/pisciner to bot session

[ REMOVE ] <login> //! Removes a student/pisciner from bot session

[ STATUS ] <login> //! Returns currect status, and quantity of
breaks already used

[ BTH ] <login> //! Sets status of student/pisciner
if break is available, else sends "break unavailable"

[ PRAR ] <login> //! Sets status of student/pisciner
if break is available, else sends "break unavailable"

[ EMG ] <login> //! Sets status of student/pisciner to
EMERGENCY break

[ FINISH ] <login> //! Sets status of student/pisciner to finished
exam

[ BACK ] <login> //! Sets status of student/pisciner to seated

[ MONITORING ] (on / off) //! toggles the tracking of number within
bth / prar

[ NUM ] //! shows number of people currently in bathroom
(inaccurate when monitoring is off)